"""Holonomy signatures of seamless parametrizations.

Conventions (see ``docs/dictionary.md``)
----------------------------------------
A seamless parametrization of a closed oriented genus-``g`` surface ``M`` with
cone set ``C = {c_1, ..., c_n}`` induces a flat cone metric on ``M`` whose
transition maps lie in ``Z_4 |x R^2`` (rotations by multiples of pi/2 plus
translations).  Its *holonomy signature* is

* the cone angles ``theta_i = (m_i + 4) * pi/2``, recorded by the integers
  ``m_i > -4`` (``m_i = 0`` is a regular marked point), and
* the rotational holonomy ``rho: H_1(M \\ C; Z) -> Z_4`` recorded by its values
  on a symplectic basis ``a_1, b_1, ..., a_g, b_g``.

``rho`` on the loop around ``c_i`` is forced: ``rho(gamma_i) = m_i mod 4``.
Gauss-Bonnet forces ``sum_i m_i = 4 * (2g - 2)``, hence ``sum_i rho(gamma_i) = 0``
in ``Z_4``, which is exactly the relation ``sum_i gamma_i = 0`` in ``H_1(M \\ C)``.

The integer ``m_i`` is simultaneously the graphics "cone index" (up to sign and
normalization) and the order of the corresponding zero/pole of a meromorphic
4-differential; that coincidence is the whole point of this project.
"""

from __future__ import annotations

from dataclasses import dataclass
from math import gcd
from typing import Iterable, Sequence

__all__ = ["Signature", "subgroup_generator", "SUBGROUP_NAMES"]

# A subgroup of Z_4 is cyclic, generated by d in {1, 2, 4}:
#   d = 1  ->  <1> = Z_4        (order 4)
#   d = 2  ->  <2> = {0, 2}     (order 2)
#   d = 4  ->  <0> = {0}        (order 1)
SUBGROUP_NAMES = {1: "Z_4", 2: "2Z_4", 4: "0"}


def subgroup_generator(values: Iterable[int]) -> int:
    """Generator ``d in {1, 2, 4}`` of the subgroup of ``Z_4`` spanned by ``values``."""
    d = 4
    for v in values:
        d = gcd(d, v % 4)
    return 4 if d == 0 else d


@dataclass(frozen=True)
class Signature:
    """A holonomy signature ``(g, m, rho)``.

    Parameters
    ----------
    genus:
        Genus of the closed oriented surface.
    orders:
        The integers ``m_i > -4``; cone angle is ``(m_i + 4) * pi / 2``.
        ``m_i = 0`` denotes a regular marked point and is allowed.
    handle_rotations:
        ``(rho(a_1), rho(b_1), ..., rho(a_g), rho(b_g))`` in ``Z_4``.
    """

    genus: int
    orders: tuple[int, ...]
    handle_rotations: tuple[int, ...]

    def __post_init__(self) -> None:
        if self.genus < 0:
            raise ValueError("genus must be >= 0")
        if len(self.handle_rotations) != 2 * self.genus:
            raise ValueError(
                f"expected {2 * self.genus} handle rotations, got {len(self.handle_rotations)}"
            )
        if any(m <= -4 for m in self.orders):
            raise ValueError("orders must be > -4 (cone angle must be positive)")
        if sum(self.orders) != 4 * (2 * self.genus - 2):
            raise ValueError(
                "Gauss-Bonnet violated: sum(orders) must equal 4*(2g-2) = "
                f"{4 * (2 * self.genus - 2)}, got {sum(self.orders)}"
            )
        if any(r % 4 != r for r in self.handle_rotations):
            raise ValueError("handle rotations must already be reduced mod 4")

    # ---------------------------------------------------------------- basics

    @property
    def n_cones(self) -> int:
        """Number of genuine cones (marked points with ``m_i = 0`` excluded)."""
        return sum(1 for m in self.orders if m != 0)

    def cone_angles_in_quarter_turns(self) -> tuple[int, ...]:
        """Cone angles as integer multiples of ``pi/2`` (i.e. quad-mesh valences)."""
        return tuple(m + 4 for m in self.orders)

    def puncture_rotations(self) -> tuple[int, ...]:
        """``rho`` on the loops around the cones, forced to be ``m_i mod 4``."""
        return tuple(m % 4 for m in self.orders)

    # -------------------------------------------------- the two Z_4 subgroups

    def cone_subgroup(self) -> int:
        """Generator of ``D = <m_i mod 4>``, the subgroup forced by the cone angles."""
        return subgroup_generator(self.orders)

    def rho_subgroup(self) -> int:
        """Generator of ``image(rho) <= Z_4``.

        ``image(rho)`` is spanned by the cone rotations together with the handle
        rotations, so it always contains ``D``.
        """
        return subgroup_generator(tuple(self.orders) + tuple(self.handle_rotations))

    # --------------------------------------------------- differential reduction

    @property
    def differential_order(self) -> int:
        """``k = 4 / d`` where ``d`` generates ``image(rho)``.

        ``k = 4``: primitive 4-differential (genuine quarter-translation surface).
        ``k = 2``: square of a primitive quadratic differential (half-translation).
        ``k = 1``: fourth power of an abelian differential (translation surface).
        """
        return 4 // self.rho_subgroup()

    def reduced_orders(self) -> tuple[int, ...]:
        """Orders of the reduced ``k``-differential: ``mu_i = m_i / d``."""
        d = self.rho_subgroup()
        if any(m % d for m in self.orders):
            raise AssertionError(
                "inconsistent signature: image(rho) does not divide all orders"
            )
        return tuple(m // d for m in self.orders)

    # ----------------------------------------------------------- MCG invariant

    def orbit_invariant(self) -> tuple[int, tuple[int, ...], int]:
        """Complete invariant of the ``MCG(M, C)``-orbit of this signature.

        See ``docs/reduction.md`` (Reduction Lemma): the orbit is determined by
        the genus, the *multiset* of orders, and ``image(rho)``.  Realizability
        is an orbit invariant, so this triple is all that the existence question
        can possibly depend on.
        """
        return (self.genus, tuple(sorted(self.orders)), self.rho_subgroup())

    def __str__(self) -> str:
        d = self.rho_subgroup()
        return (
            f"g={self.genus} m={list(self.orders)} "
            f"rho={list(self.handle_rotations)} "
            f"im(rho)={SUBGROUP_NAMES[d]} k={self.differential_order}"
        )


def signatures_with_orders(
    genus: int, orders: Sequence[int]
) -> "list[Signature]":
    """All signatures with the given genus and orders (brute force over ``rho``)."""
    from itertools import product

    return [
        Signature(genus, tuple(orders), rho)
        for rho in product(range(4), repeat=2 * genus)
    ]
